#
spring.application.name=student-attendance
server.port=${SERVER_PORT:8765}
server.servlet.session.timeout=3h
server.servlet.session.persistent=false
server.forward-headers-strategy=framework

# Connection to MySQL
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:student_attendance}?serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.format_sql=true

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}

# Mail Configuration
spring.mail.name=${MAILER_NAME:S-FaceTrack}
spring.mail.username=${MAILER_USERNAME}
spring.mail.password=${MAILER_PASSWORD}
spring.mail.host=${MAILER_HOST:smtp.gmail.com}
spring.mail.port=${MAILER_PORT:587}
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true

# Database Generator
db.fake.isGenerated=${DB_GENERATOR:false}
db.fake-user-name=${DB_USER_NAME}
db.fake-user-code=${DB_USER_CODE}
db.fake-user-email=${DB_USER_EMAIL}
db.fake-facility=${DB_FACILITY_NAME}

# Server Allowed Origin
allowed.origin=${SERVER_ALLOWED_ORIGIN:*}

# Authentication Secret Key
authentication.secret-key=${AUTHENTICATION_SECRET_KEY}

# App Settings
app.config.app-name=${APP_CONFIG_APP_NAME:Student Attendance}
app.config.allows-one-teacher-to-teach-multiple-classes=${APP_CONFIG_ALLOWS_ONE_TEACHER_TO_TEACH_MULTIPLE_CLASESS:false}

# Cron configuration for automatic statistics email
app.config.cron.statistics-email=${APP_CONFIG_CRON_STATISTICS_EMAIL}
app.config.email.statistics.enabled=${APP_CONFIG_EMAIL_STATISTICS_ENABLED}
app.config.face.threshold_checkin=${APP_CONFIG_FACE_THRESHOLD_CHECKIN:0.4}
app.config.face.threshold_register=${APP_CONFIG_FACE_THRESHOLD_REGISTER:0.35}
app.config.path.model=${APP_CONFIG_PATH_MODEL:model}

# Logging Configuration
logging.file.path=${LOG_PATH}
logging.file.name=${LOG_FILE}
logging.pattern.file=${LOG_PATTERN}
logging.level.org.hibernate.orm.connections.pooling=WARN

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6378}
spring.cache.type=redis
spring.cache.redis.cache-null-values=true
spring.data.redis.repositories.enabled=false
spring.cache.redis.time-to-live=${REDIS_TTL:259200}

#Actuator
management.health.redis.enabled=false

# Disable Redis repository auto-configuration
spring.web.resources.cache.cachecontrol.no-cache=false
spring.web.resources.cache.cachecontrol.max-age=3600

# Banner
spring.banner.location=banner/banner.txt

# Encoding settings
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Multipart Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB



